apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
      - name: drone-runner
        image: drone/drone-runner-kube:latest
        env:
        - name: DRONE_RPC_HOST
          value: "drone-server"  # Should match the service name of the Drone server
        - name: DRONE_RPC_PROTO
          value: "http"  # Change to "https" if you're using HTTPS
        - name: DRONE_RPC_SECRET
          value: "enter yout rpc secret"  # Replace with your Drone RPC secret
        - name: DRONE_RUNNER_CAPACITY
          value: "2"  # Number of concurrent builds the runner can handle
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock

