apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - name: drone-server
        image: drone/drone:latest
        ports:
        - containerPort: 80
        env:
        - name: DRONE_SERVER_HOST
          value: "drone-server"  # Replace with your Drone server host
        - name: DRONE_SERVER_PROTO
          value: "http"  # Change to "https" if you're using HTTPS
        - name: DRONE_GITHUB_CLIENT_ID
          value: "e7a4ebcdc9057eb6d0e3"  # Replace with your GitHub client ID
        - name: DRONE_GITHUB_CLIENT_SECRET
          value: "b7fad9305ae96ab34ccd8b2e52682f0d6e9c820f"  # Replace with your GitHub client secret
        - name: DRONE_RPC_SECRET
          value: "25988de9b5d45de8f7b37d0950341286"  # Replace with your Drone RPC secret
