apiVersion: v1
kind: Service
metadata:
  name: drone-server
spec:
  type: NodePort
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # You can change this to any available port you prefer
