apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - name: drone-server
        image: drone/drone
        ports:
        - containerPort: 80
        env:
        - name: DRONE_SERVER_HOST
          value: "drone-server"  # Replace with your Drone server host
        - name: DRONE_SERVER_PROTO
          value: "http"  # Change to "https" if you're using HTTPS
        - name: DRONE_GITHUB_CLIENT_ID
          value: "enter your github client id"  # Replace with your GitHub client ID
        - name: DRONE_GITHUB_CLIENT_SECRET
          value: "enter your client secret"  # Replace with your GitHub client secret
        - name: DRONE_RPC_SECRET
          value: "enter your rpc secret"  # Replace with your Drone RPC secret
